### ISSUE TITLE
Spurious CONNECTED interrupts from USBDEV when rv_timer is enabled

### ISSUE THREAD

**Issue by phil-levis** [lowRISC/opentitan#3388]
I ran into this when working on the new timer system for the Tock operating system.

If using master (60138bdcbef67), then setting up rv_timer interrupts causes USBDEV to issue CONNECTED interrupts. These interrupts cannot be masked or disabled in the USBDEV peripheral; they seem to have to be masked in the PLIC. 

Here is a Tock branch that exhibits this problem:

https://github.com/tock/tock/tree/opentitan-alarm-causes-usb-failures

@alistair23  has verified that #2753 fixes this issue. So we haven't dug too deeply into it. I've submitted a workaround PR for Tock https://github.com/tock/tock/pull/2100 . We will just mask USBDEV interrupts in the PLIC until USBDEV is behaving properly. But we wanted to enter it the issue here for bookkeeping purposes.

**Comment by vogelpi** [comment]
Hi @phil-levis,
thanks for reporting the issue here.

As you stated, with #2753 the issue is fixed. However, I am not sure if it just avoids the problematic behavior and there is still an actual bug related to the interrupts here. Maybe it would be useful to check some things, just to be sure.
- Looking at the usbdev source code and documentation, I can say that CONNECTED interrupt inside the usbdev can be disabled at the device level. To this end, bit 15 in usbdev.INTR_ENABLE should be set to 0.
- CONNECTED interrupts can only be re-triggered in the hardware upon hardware resets (`rst_ni`), or if the USB sense signal is flaky. Otherwise only a single interrupt should be seen. According to the description here https://github.com/lowRISC/opentitan/pull/2753#issue-446555841, without #2753 a flipped pullup will make the link look like a low-speed instead of full-speed device to the host. The 1.5 Mbit chatter then triggers receive PID errors and keeps resetting the link. This is what PR #2753 addresses but it's not like a hardware reset. I am wondering how these link resets lead to CONNECTED interrupts.
- I am wondering how this all depends on rv_timer interrupts. They way these interrupts are handled in the system is pretty different. The rv_timer interrupt line is directly connected to the core (timer interrupt line) whereas all other interrupts are connected through the PLIC and then signaled to the core via the external interrupt line. Just because timer interrupts are enabled doesn't mean anything from the PLIC can or should be signaled. There are separate bits in the `mie` CSR of the core.

**Comment by phil-levis** [comment]
I'll try to dig some more. I found that I could not disable the CONNECTED interrupt inside USBDEV.

**Comment by vogelpi** [comment]
We have just merged #3359 which supersedes #2753 and should fix this bug as well.

However, as outlined in my previous comment, I think there could still be a different problem in software.

**Comment by alistair23** [comment]
I just checked this.

Using the bitstream from 4429c362900713c059fbd870db140e0058e1c0eb, which includes both https://github.com/lowRISC/opentitan/pull/3692 and https://github.com/lowRISC/opentitan/pull/3359 I see constant and unending USBDEV_CONNECTED (0x4F) interrupts.

Even disabling interrupts in the USB module by writing zeros to `usbdev.INTR_ENABLE` doesn't disable the interrupt.

**Comment by vogelpi** [comment]
Hey @alistair23 ,
thanks for trying this out again. This sounds bad :-(

Unfortunately, I cannot verify correct USB functionality on the FPGA as I do not yet have the required adapter board. However, I just did some tests using the Verilator simulation and the hello_usbdev example application (`sw/device/examples/hello_usbdev`). By default, this test application does not use interrupts and disables all of them, see `sw/device/lib/usbdev.c` Line 268:
```
  // All about polling...
  REG32(USBDEV_INTR_ENABLE()) = 0;
```
In simulation, I could see the `event_connect` being produced exactly once but the `intr_connected_o` interrupt is not generated. If I change the line in  `sw/device/lib/usbdev.c` to `  REG32(USBDEV_INTR_ENABLE()) = 0xFFFFFFFF;` I get exactly one interrupt. So all seems right from this perspective.

However, doing a quick check on the FPGA (without anything connected to USB) and just poilling and clearing `USBDEV_INTR_STATE()` I also see the CONNECTED bit being constantly set. This indeed indicates that on the FPGA we get those `event_connect` events all the time. So this definitely needs to be investigated.

Regarding the signaling of the interrupt itself, I just noticed that if you disable the interrupt at the device (setting `usbdev.INTR_ENABLE` to 0) just means the interrupt should not be signaled, to the PLIC and then the processor. But the interrupt is still registered inside `usbdev.INTR_STATE`. Related to that, I have two questions:
1. Just to be 100% sure, do you really get the interrupt, or is your software just polling `usbdev.INTR_STATE`?
2. Did you try to disable the PLIC interrupt input at the core? For this you need to set the MEIE bit (bit 11) in the mie CSR to 0. This should disable all interrupts from the PLIC.

**Comment by mdhayter** [comment]
Pure speculation at this point, have not looked at the code. The usbdev detects the VBUS to tell if there is a host attached (per USB spec). On the PMOD this is done by resistor-dividing the 5V VBUS (by 2) to give a signal that is safe for 0/1 into the 3.3V FPGA pin. If there is no PMOD then we could have a floating input? Pure speculation if it reads as 1 then the host is detected and sw/hw start doing things. I think the new state machine would worst case get stuck in the new active-no-sof state. 

The PMOD usse 5.1k - 5.1k divider. If the internal pull-down in parallel with the low side 5.1k still results in a voltage above Vih(min) with 4.5V on VBUS then just enabling the pull-down could be a fix. (If it does not then it would fix the no-PMOD but would require resistor changes on the PMOD).

Again, at this point I didn't look at code so this is speculation.

**Comment by alistair23** [comment]
Hey @vogelpi thanks for looking into this.

Just to clarify you don't need the USB adapter board to see the problems. Without it connected I still see the interrupts.

1. I'm sure we are getting the interrupt because in Tock the USB `handle_interrupt()` function is only called if the PLIC gets an interrupt.
2. If the interrupts are disabled in the PLIC with the PLIC `enable` register they don't trigger interrupts. I'm assuming that disabling external interrupts with `MEIE` will also have the same effect. The problem is that with interrupts enabled in the PLIC there is no way to disable them in the USB device.

**Comment by vogelpi** [comment]
Thanks @mdhayter and @alistair23 for getting back. It sounds as if we have two issues here:
1. Why USB generates the connected event signal.
2. Why the interrupt generation cannot be disabled on FPGA. There could be a more general issue with the `prim_intr_hw` primitive not being properly synthesized on FPGA.

**Comment by tjaychen** [comment]
is this still an issue.. ?

**Comment by alistair23** [comment]
It seems to be fixed now
