### ISSUE TITLE
Fusesoc conflicting requirements

### ISSUE THREAD

**Issue by camaabdo** [lowRISC/opentitan#9631]
Hello,

I need help with this problem. I am working on a student project in my last year of school. When I try to run FuseSoC with the open titan platform, I have this problem appear, and my work tree is clean.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/55259057/145575190-27575c91-c584-4e63-86ad-8a7ba6b0be4d.png">

Thanks for your help

**Comment by rswarbrick** [comment]
I think this probably means you're using the wrong version of fusesoc. Can you check that you've installed the "ot" flavour? (The easiest way is to run `python3 -m pip install -r python-requirements.txt` at top-level in the repository.

**Comment by camaabdo** [comment]
Thank you for your answer,
When I launch this command, on the TOP, here is the result.

MacBook-Pro-de-cabd:opentitan cabd$ python3 -m pip install -r python-requirements.txt
Collecting fusesoc>=1.12.0
  Cloning https://github.com/lowRISC/fusesoc.git (to revision ot) to /private/var/folders/pb/xlj_z6gn5rjdvd4z5dx208mc0000gn/T/pip-install-6soa8vx0/fusesoc_e9ec884c5e354477a60fa528def65204
  Running command git clone -q https://github.com/lowRISC/fusesoc.git /private/var/folders/pb/xlj_z6gn5rjdvd4z5dx208mc0000gn/T/pip-install-6soa8vx0/fusesoc_e9ec884c5e354477a60fa528def65204
  Running command git checkout -b ot --track origin/ot
  Basculement sur la nouvelle branche 'ot'
  La branche 'ot' est paramétrée pour suivre la branche distante 'ot' depuis 'origin'.
  Resolved https://github.com/lowRISC/fusesoc.git to commit 14dfc825ced58fe1fb343662fa80fc4fbd0fdc50
  WARNING: Requested fusesoc>=1.12.0 from git+https://github.com/lowRISC/fusesoc.git@ot#egg=fusesoc >= 1.12.0 (from -r python-requirements.txt (line 45)), but installing version 1.12.1.dev31+g14dfc82
Collecting edalize>=0.2.4
  Cloning https://github.com/lowRISC/edalize.git (to revision ot) to /private/var/folders/pb/xlj_z6gn5rjdvd4z5dx208mc0000gn/T/pip-install-6soa8vx0/edalize_3ba217caf124461eaaeaf5e12cd6433d
  Running command git clone -q https://github.com/lowRISC/edalize.git /private/var/folders/pb/xlj_z6gn5rjdvd4z5dx208mc0000gn/T/pip-install-6soa8vx0/edalize_3ba217caf124461eaaeaf5e12cd6433d
  Running command git checkout -b ot --track origin/ot
  Basculement sur la nouvelle branche 'ot'
  La branche 'ot' est paramétrée pour suivre la branche distante 'ot' depuis 'origin'.
  Resolved https://github.com/lowRISC/edalize.git to commit 23e1beab41508e13c565125e5edcadb86b0032f6
Collecting https://github.com/newaetech/chipwhisperer/archive/9b6825b495f14f85aae8b11007c63c59a1654584.tar.gz (from -r python-requirements.txt (line 56))
  Using cached https://github.com/newaetech/chipwhisperer/archive/9b6825b495f14f85aae8b11007c63c59a1654584.tar.gz
Requirement already satisfied: anytree in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 6)) (2.8.0)
Requirement already satisfied: enlighten in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 7)) (1.10.1)
Requirement already satisfied: flake8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 8)) (4.0.1)
Requirement already satisfied: git-fame in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 9)) (1.15.1)
Requirement already satisfied: gitpython in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 10)) (3.1.24)
Requirement already satisfied: hjson in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 11)) (3.0.2)
Requirement already satisfied: ipyxact>=0.2.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 12)) (0.2.4)
Requirement already satisfied: isort in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 13)) (5.10.1)
Requirement already satisfied: libcst in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 14)) (0.3.23)
Requirement already satisfied: livereload in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 15)) (2.6.3)
Requirement already satisfied: mako in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 16)) (1.1.6)
Requirement already satisfied: meson<=0.54,>=0.53.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 17)) (0.54.0)
Requirement already satisfied: mistletoe>=0.7.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 18)) (0.7.2)
Requirement already satisfied: mypy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 19)) (0.910)
Requirement already satisfied: premailer<3.9.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 24)) (3.8.0)
Requirement already satisfied: pycryptodome>=3.11.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 25)) (3.12.0)
Requirement already satisfied: pydriller in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 26)) (2.0)
Requirement already satisfied: pyelftools in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 27)) (0.27)
Requirement already satisfied: pyftdi in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 28)) (0.53.3)
Requirement already satisfied: pyserial in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 29)) (3.5)
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 30)) (2.10.0)
Requirement already satisfied: pytest in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 31)) (6.2.5)
Requirement already satisfied: pytest-timeout in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 32)) (2.0.1)
Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 33)) (6.0)
Requirement already satisfied: tabulate in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 34)) (0.8.9)
Requirement already satisfied: termcolor in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 35)) (1.1.0)
Requirement already satisfied: yapf in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 36)) (0.31.0)
Requirement already satisfied: types-dataclasses in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 39)) (0.6.1)
Requirement already satisfied: types-pkg_resources in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 40)) (0.1.3)
Requirement already satisfied: types-pyyaml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 41)) (6.0.1)
Requirement already satisfied: types-tabulate in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r python-requirements.txt (line 42)) (0.8.3)
Requirement already satisfied: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from anytree->-r python-requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: blessed>=1.17.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from enlighten->-r python-requirements.txt (line 7)) (1.19.0)
Requirement already satisfied: prefixed>=0.3.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from enlighten->-r python-requirements.txt (line 7)) (0.3.2)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from flake8->-r python-requirements.txt (line 8)) (0.6.1)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from flake8->-r python-requirements.txt (line 8)) (2.8.0)
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from flake8->-r python-requirements.txt (line 8)) (2.4.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from git-fame->-r python-requirements.txt (line 9)) (57.4.0)
Requirement already satisfied: argopt>=0.3.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from git-fame->-r python-requirements.txt (line 9)) (0.7.0)
Requirement already satisfied: tqdm>=4.44.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from git-fame->-r python-requirements.txt (line 9)) (4.62.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from gitpython->-r python-requirements.txt (line 10)) (4.0.9)
Requirement already satisfied: typing-inspect>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from libcst->-r python-requirements.txt (line 14)) (0.7.1)
Requirement already satisfied: typing-extensions>=3.7.4.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from libcst->-r python-requirements.txt (line 14)) (4.0.1)
Requirement already satisfied: tornado in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from livereload->-r python-requirements.txt (line 15)) (6.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mako->-r python-requirements.txt (line 16)) (2.0.1)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mypy->-r python-requirements.txt (line 19)) (0.4.3)
Requirement already satisfied: toml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from mypy->-r python-requirements.txt (line 19)) (0.10.2)
Requirement already satisfied: lxml in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from premailer<3.9.0->-r python-requirements.txt (line 24)) (4.6.4)
Requirement already satisfied: cssselect in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from premailer<3.9.0->-r python-requirements.txt (line 24)) (1.1.0)
Requirement already satisfied: cssutils in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from premailer<3.9.0->-r python-requirements.txt (line 24)) (2.3.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from premailer<3.9.0->-r python-requirements.txt (line 24)) (2.26.0)
Requirement already satisfied: cachetools in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from premailer<3.9.0->-r python-requirements.txt (line 24)) (4.2.4)
Requirement already satisfied: lizard in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pydriller->-r python-requirements.txt (line 26)) (1.17.9)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pydriller->-r python-requirements.txt (line 26)) (2021.3)
Requirement already satisfied: pyusb!=1.2.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyftdi->-r python-requirements.txt (line 28)) (1.2.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest->-r python-requirements.txt (line 31)) (1.0.0)
Requirement already satisfied: py>=1.8.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest->-r python-requirements.txt (line 31)) (1.11.0)
Requirement already satisfied: attrs>=19.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest->-r python-requirements.txt (line 31)) (21.2.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest->-r python-requirements.txt (line 31)) (21.3)
Requirement already satisfied: iniconfig in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest->-r python-requirements.txt (line 31)) (1.1.1)
Requirement already satisfied: pyparsing in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from fusesoc>=1.12.0->-r python-requirements.txt (line 45)) (3.0.6)
Requirement already satisfied: simplesat>=0.8.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from fusesoc>=1.12.0->-r python-requirements.txt (line 45)) (0.8.2)
Requirement already satisfied: Jinja2>=2.11.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from edalize>=0.2.4->-r python-requirements.txt (line 48)) (3.0.3)
Requirement already satisfied: configobj in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from chipwhisperer==5.5.2->-r python-requirements.txt (line 56)) (5.0.6)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from chipwhisperer==5.5.2->-r python-requirements.txt (line 56)) (1.21.4)
Requirement already satisfied: ECpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from chipwhisperer==5.5.2->-r python-requirements.txt (line 56)) (1.2.5)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from chipwhisperer==5.5.2->-r python-requirements.txt (line 56)) (1.7.3)
Requirement already satisfied: fastdtw in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from chipwhisperer==5.5.2->-r python-requirements.txt (line 56)) (0.3.4)
Requirement already satisfied: Cython in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from chipwhisperer==5.5.2->-r python-requirements.txt (line 56)) (0.29.24)
Requirement already satisfied: wcwidth>=0.1.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from blessed>=1.17.7->enlighten->-r python-requirements.txt (line 7)) (0.2.5)
Requirement already satisfied: smmap<6,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython->-r python-requirements.txt (line 10)) (5.0.0)
Requirement already satisfied: okonomiyaki>=0.16.6 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from simplesat>=0.8.0->fusesoc>=1.12.0->-r python-requirements.txt (line 45)) (1.3.2)
Requirement already satisfied: jsonschema>=2.5.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.12.0->-r python-requirements.txt (line 45)) (4.2.1)
Requirement already satisfied: zipfile2>=0.0.12 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.12.0->-r python-requirements.txt (line 45)) (0.0.12)
Requirement already satisfied: distro in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.12.0->-r python-requirements.txt (line 45)) (1.6.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc>=1.12.0->-r python-requirements.txt (line 45)) (0.18.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->premailer<3.9.0->-r python-requirements.txt (line 24)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->premailer<3.9.0->-r python-requirements.txt (line 24)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->premailer<3.9.0->-r python-requirements.txt (line 24)) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->premailer<3.9.0->-r python-requirements.txt (line 24)) (2.0.8)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install --upgrade pip' command.

**Comment by msfschaffner** [comment]
@camaabdo could you resolve the problem by now or does the issue still persist?
